name: Hoyolab Auto Sign
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Run ZZZ sign
        env:
          HOYOLAB_TOKEN: ${{{{ secrets.HOYOLAB_TOKEN }}}}
          ZZZ: true
          ZZZ_UID: "20150166"
          ACCOUNT_NAME: "My Account"
        run: |
          pip install requests -q
          python hoyo_sign.py
